version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: invoice-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - invoice-network

  backend:
    build: ./backend
    container_name: invoice-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/invoice_db
    depends_on:
      - mongodb
    networks:
      - invoice-network

  frontend:
    build: ./frontend
    container_name: invoice-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - invoice-network

volumes:
  mongo-data:

networks:
  invoice-network:
    driver: bridge
